# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-File-Find-Rule
version:      1.00
version_from: lib/Test/File/Find/Rule.pm
installdirs:  site
requires:
    File::Find::Rule:              0
    File::Spec:                    0
    Number::Compare:               0
    Test::Builder:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
